# Generated by Django 5.0.1 on 2024-02-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydata',
            name='adjusted_close',
        ),
    ]
